version: '2'
services:
  sensor:
    build: .
    environment:
      - 'MAX13856_CS_PINS=["D5","D13"]'
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.supervisor-api: '1'
    expose:
      - '7575'